[project]
name = "vibe-quiz-how-do-i-answer-this"
version = "0.1.0"
description = "A simple quiz server"
authors = [
    {name = "Jirawat Iamsamang", email = "nodtem66@gmail.com"}
]
requires-python = ">=3.14"
dependencies = [
    "fastapi",
    "granian",
    "pydantic",
    "openrouter",
    "qrcode"
]
license = "MIT"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"